language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install pythonanywhere
script: python -m unittest test_hello.py

deploy:
  provider: script
  script: ./deploy_pythonanywhere.sh
  on:
    branch: master
    python: 3.8
  skip_cleanup: true

